INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Catar' ),2022,null);
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Rusia' ),2018,(Select id from pais where nombre = 'Francia'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Uruguay' ),1930,(Select id from pais where nombre = 'Uruguay'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Brasil' ),1950,(Select id from pais where nombre = 'Uruguay'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Francia' ),1938,(Select id from pais where nombre = 'Italia'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Italia' ),1934,(Select id from pais where nombre = 'Italia'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Suiza' ),1954,(Select id from pais where nombre = 'Alemania Occidental'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Inglaterra' ),1966,(Select id from pais where nombre = 'Inglaterra'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Chile' ),1962,(Select id from pais where nombre = 'Brasil'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Suecia' ),1958,(Select id from pais where nombre = 'Brasil'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'México' ),1970,(Select id from pais where nombre = 'Brasil'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'España' ),1982,(Select id from pais where nombre = 'Italia'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Alemania Occidental' ),1974,(Select id from pais where nombre = 'Alemania Occidental'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Argentina' ),1978,(Select id from pais where nombre = 'Argentina'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Italia' ),1990,(Select id from pais where nombre = 'Alemania Occidental'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'México' ),1986,(Select id from pais where nombre = 'Argentina'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Estados Unidos' ),1994,(Select id from pais where nombre = 'Brasil'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Francia' ),1998,(Select id from pais where nombre = 'Francia'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Corea / Japón' ),2002,(Select id from pais where nombre = 'Brasil'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Sudáfrica' ),2010,(Select id from pais where nombre = 'España'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Alemania' ),2006,(Select id from pais where nombre = 'Italia'));
INSERT INTO mundial (sede,year,campeon) values ((SELECT id from pais where nombre = 'Brasil' ),2014,(Select id from pais where nombre = 'Alemania'));
