INSERT INTO pais (nombre) values ('Alemania');
INSERT INTO pais (nombre) values ('Alemania Oriental');
INSERT INTO pais (nombre) values ('Angola');
INSERT INTO pais (nombre) values ('Arabia Saudita');
INSERT INTO pais (nombre) values ('Argelia');
INSERT INTO pais (nombre) values ('Argentina');
INSERT INTO pais (nombre) values ('Australia');
INSERT INTO pais (nombre) values ('Austria');
INSERT INTO pais (nombre) values ('Bélgica');
INSERT INTO pais (nombre) values ('Bolivia');
INSERT INTO pais (nombre) values ('Bosnia-Herzegovina');
INSERT INTO pais (nombre) values ('Brasil');
INSERT INTO pais (nombre) values ('Bulgaria');
INSERT INTO pais (nombre) values ('Camerún');
INSERT INTO pais (nombre) values ('Canadá');
INSERT INTO pais (nombre) values ('Catar');
INSERT INTO pais (nombre) values ('Chile');
INSERT INTO pais (nombre) values ('China');
INSERT INTO pais (nombre) values ('Colombia');
INSERT INTO pais (nombre) values ('Corea del Norte');
INSERT INTO pais (nombre) values ('Corea del Sur');
INSERT INTO pais (nombre) values ('Costa de Marfil');
INSERT INTO pais (nombre) values ('Costa Rica');
INSERT INTO pais (nombre) values ('Croacia');
INSERT INTO pais (nombre) values ('Cuba');
INSERT INTO pais (nombre) values ('Dinamarca');
INSERT INTO pais (nombre) values ('Ecuador');
INSERT INTO pais (nombre) values ('Egipto');
INSERT INTO pais (nombre) values ('El Salvador');
INSERT INTO pais (nombre) values ('Emiratos Arabes');
INSERT INTO pais (nombre) values ('Escocia');
INSERT INTO pais (nombre) values ('Eslovaquia');
INSERT INTO pais (nombre) values ('Eslovenia');
INSERT INTO pais (nombre) values ('España');
INSERT INTO pais (nombre) values ('Estados Unidos');
INSERT INTO pais (nombre) values ('Francia');
INSERT INTO pais (nombre) values ('Gales');
INSERT INTO pais (nombre) values ('Ghana');
INSERT INTO pais (nombre) values ('Grecia');
INSERT INTO pais (nombre) values ('Haití');
INSERT INTO pais (nombre) values ('Holanda');
INSERT INTO pais (nombre) values ('Honduras');
INSERT INTO pais (nombre) values ('Hungría');
INSERT INTO pais (nombre) values ('Indonesia');
INSERT INTO pais (nombre) values ('Inglaterra');
INSERT INTO pais (nombre) values ('Irán');
INSERT INTO pais (nombre) values ('Iraq');
INSERT INTO pais (nombre) values ('Irlanda');
INSERT INTO pais (nombre) values ('Irlanda del Norte');
INSERT INTO pais (nombre) values ('Islandia');
INSERT INTO pais (nombre) values ('Israel');
INSERT INTO pais (nombre) values ('Italia');
INSERT INTO pais (nombre) values ('Jamaica');
INSERT INTO pais (nombre) values ('Japón');
INSERT INTO pais (nombre) values ('Kuwait');
INSERT INTO pais (nombre) values ('Marruecos');
INSERT INTO pais (nombre) values ('México');
INSERT INTO pais (nombre) values ('Nigeria');
INSERT INTO pais (nombre) values ('Noruega');
INSERT INTO pais (nombre) values ('Nueva Zelanda');
INSERT INTO pais (nombre) values ('Panama');
INSERT INTO pais (nombre) values ('Paraguay');
INSERT INTO pais (nombre) values ('Perú');
INSERT INTO pais (nombre) values ('Polonia');
INSERT INTO pais (nombre) values ('Portugal');
INSERT INTO pais (nombre) values ('RD Congo');
INSERT INTO pais (nombre) values ('Republica Checa');
INSERT INTO pais (nombre) values ('Rumania');
INSERT INTO pais (nombre) values ('Rusia');
INSERT INTO pais (nombre) values ('Senegal');
INSERT INTO pais (nombre) values ('Serbia');
INSERT INTO pais (nombre) values ('Sudáfrica');
INSERT INTO pais (nombre) values ('Suecia');
INSERT INTO pais (nombre) values ('Suiza');
INSERT INTO pais (nombre) values ('Togo');
INSERT INTO pais (nombre) values ('Trinidad y Tobago');
INSERT INTO pais (nombre) values ('Túnez');
INSERT INTO pais (nombre) values ('Turquía');
INSERT INTO pais (nombre) values ('Ucrania');
INSERT INTO pais (nombre) values ('Uruguay');
